---
name: Check ðŸ“¦

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

concurrency:
  group: check-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-test:
    name: ${{ vars.CI_IMAGE }}
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}

    steps:
      - name: Checkout project â¬‡ï¸
        uses: actions/checkout@v4

      - name: Install package dependencies ðŸ“„
        uses: boehringer-ingelheim/dv.templates/.github/actions/dependencies@main

      - name: Check ðŸ“¦
        run: |
          options(crayon.enabled = TRUE)
          devtools::check(error_on="error", args=c("--no-tests"))
        shell: Rscript {0}

      - name: Test ðŸ§ª
        if: >
          ${{ !contains(github.event.commits[0].message, '[skip tests]') && github.event.pull_request.draft == false }}
        run: |
          options(crayon.enabled = TRUE)
          devtools::test(stop_on_failure = TRUE)
        shell: Rscript {0}

