---
name: Roxygen üìÑ

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

concurrency:
  group: roxygen-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  roxygen:
    name: ${{ vars.CI_IMAGE }}
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}

    steps:
      - name: Checkout project ‚¨áÔ∏è
        uses: actions/checkout@v4

      - name: Install package dependencies üìÑ
        uses: boehringer-ingelheim/dv.templates/.github/actions/dependencies@main

      - name: Generate man pages üìÑ
        run: |
          Rscript -e 'roxygen2::roxygenize()'
          if [[ -n $(git status -s | grep -E "man|DESCRIPTION") ]]
          then
            ROXYGEN_VERSION="$(Rscript -e 'packageVersion("roxygen2")' | awk '{print $NF}')"
            echo "‚ö†Ô∏è Manuals are not up-to-date with roxygen comments!"
            echo "Here are the differences:"
            git diff man/* DESCRIPTION
            echo -e "\n Please rerun the following command on your workstation and push your changes"
            echo "--------------------------------------------------------------------"
            echo "roxygen2::roxygenize('.')"
            echo "--------------------------------------------------------------------"
            echo "‚ÑπÔ∏è roxygen2 version that was used in this workflow: $ROXYGEN_VERSION"
            echo "Please ensure that the 'RoxygenNote' field in the DESCRIPTION file matches this version"
            exit 1
          else
            echo "üëç Manuals are up-to-date with roxygen comments"
          fi
        shell: bash
