---
name: Checks ğŸ§©

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

jobs:
  check:
    name: Check ğŸ“¦
    uses: zsigmas/dv.templates/.github/workflows/check.yml@test

  test:
    name: Test and QC ğŸ§ª
    uses: zsigmas/dv.templates/.github/workflows/test.yml@test

  lintr:
    name: Lintr ğŸ”
    uses: zsigmas/dv.templates/.github/workflows/lintr.yml@test
    with:
      lintr_error_on_lint: true

  gitleaks:
    name: Gitleaks ğŸŒ§ï¸
    uses: zsigmas/dv.templates/.github/workflows/gitleaks.yml@test

  roxygen:
    name: Roxygen ğŸ“„
    uses: zsigmas/dv.templates/.github/workflows/roxygen.yml@test

  pkgdown:
    name: Pkgdown ğŸ“–
    uses: zsigmas/dv.templates/.github/workflows/pkgdown.yml@test
    needs: test

  styler:
    name: Styler ğŸŒ
    uses: zsigmas/dv.templates/.github/workflows/styler.yml@test

  release:
    name: Release ğŸ“ˆ
    uses: zsigmas/dv.templates/.github/workflows/release.yml@test
